[
{ "autoconf": {
    "name": "gmp_make",
    "configure_args": [ "--disable-assembly" ],
    "outs": [
       "$GEN_DIR/lib/libgmp.a"
     ],
    "licenses": [ "http://opensource.org/licenses/gpl-2.0",
                  "http://opensource.org/licenses/lgpl-3.0" ]
                  
  } }
]